# Generated by Django 5.0.6 on 2024-05-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='Название')),
                ('recipe_description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('stages_preparation', models.TextField(verbose_name='Этапы приготовления')),
                ('time_preparation', models.IntegerField(verbose_name='Время приготовления, мин.')),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images', verbose_name='Изображение')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Имя')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('user_date_add', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_recipes.categories', verbose_name='Категория')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_recipes.recipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепты по категориям',
                'verbose_name_plural': 'Рецепты по категориям',
            },
        ),
    ]
