# Generated by Django 5.0.6 on 2024-05-10 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='food_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='food_images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
